// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 单行歌词
class LyricLine {
  /// 时间戳（毫秒）
  final BigInt timeMs;

  /// 歌词文本
  final String text;

  const LyricLine({required this.timeMs, required this.text});

  @override
  int get hashCode => timeMs.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricLine &&
          runtimeType == other.runtimeType &&
          timeMs == other.timeMs &&
          text == other.text;
}

/// 歌词数据
class Lyrics {
  /// 歌词行列表（按时间排序）
  final List<LyricLine> lines;

  const Lyrics({required this.lines});

  @override
  int get hashCode => lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Lyrics &&
          runtimeType == other.runtimeType &&
          lines == other.lines;
}
