// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 歌曲库（本地 JSON 持久化的根结构）
class Library {
  /// 歌曲列表
  final List<Song> songs;

  /// 扫描的目录列表
  final List<String> scanDirs;

  /// 上次扫描时间戳
  final BigInt lastScanAt;

  const Library({
    required this.songs,
    required this.scanDirs,
    required this.lastScanAt,
  });

  @override
  int get hashCode => songs.hashCode ^ scanDirs.hashCode ^ lastScanAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Library &&
          runtimeType == other.runtimeType &&
          songs == other.songs &&
          scanDirs == other.scanDirs &&
          lastScanAt == other.lastScanAt;
}

/// 歌曲信息
class Song {
  /// 本地文件路径
  final String filePath;

  /// 歌曲标题
  final String title;

  /// 歌手
  final String artist;

  /// 专辑名
  final String album;

  /// 时长（秒）
  final double duration;

  /// 文件大小（字节）
  final BigInt fileSize;

  /// 文件格式（mp3/flac/wav 等）
  final String format;

  /// 在线匹配标识（兼容保留）
  final String? songmid;

  /// 在线匹配专辑标识（兼容保留）
  final String? albummid;

  /// 文件最后修改时间戳
  final BigInt modifiedAt;

  const Song({
    required this.filePath,
    required this.title,
    required this.artist,
    required this.album,
    required this.duration,
    required this.fileSize,
    required this.format,
    this.songmid,
    this.albummid,
    required this.modifiedAt,
  });

  @override
  int get hashCode =>
      filePath.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      duration.hashCode ^
      fileSize.hashCode ^
      format.hashCode ^
      songmid.hashCode ^
      albummid.hashCode ^
      modifiedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Song &&
          runtimeType == other.runtimeType &&
          filePath == other.filePath &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          duration == other.duration &&
          fileSize == other.fileSize &&
          format == other.format &&
          songmid == other.songmid &&
          albummid == other.albummid &&
          modifiedAt == other.modifiedAt;
}
