// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/cache.dart';
import 'api/metadata.dart';
import 'api/play_stats.dart';
import 'api/player.dart';
import 'api/scanner.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'models/lyrics.dart';
import 'models/song.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 2041270708;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_jmusic',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<Uint8List> crateApiMetadataGetCover({required String albummid});

  String crateApiMetadataGetCoverUrl({required String albummid});

  Library crateApiScannerGetLibrary();

  Future<Lyrics> crateApiMetadataGetLyrics({required String songmid});

  Future<Lyrics> crateApiMetadataGetNeteaseLyrics({required String id});

  int crateApiPlayStatsGetPlayCount({required String filePath});

  List<PlayCountEntry> crateApiPlayStatsGetPlayStats();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Lyrics crateApiMetadataParseLrcText({required String lrcText});

  String? crateApiPlayerPlayerGetCurrentFile();

  double crateApiPlayerPlayerGetVolume();

  void crateApiPlayerPlayerInit();

  bool crateApiPlayerPlayerIsFinished();

  void crateApiPlayerPlayerPause();

  void crateApiPlayerPlayerPlay({required String filePath});

  void crateApiPlayerPlayerResume();

  void crateApiPlayerPlayerSeek({required double positionSecs});

  void crateApiPlayerPlayerSetVolume({required double volume});

  void crateApiPlayerPlayerStop();

  Future<Uint8List?> crateApiScannerReadEmbeddedCover({
    required String filePath,
  });

  Future<String?> crateApiScannerReadEmbeddedLyrics({required String filePath});

  void crateApiPlayStatsRecordPlay({
    required String filePath,
    required String title,
    required String artist,
  });

  Future<void> crateApiCacheResetLibrary();

  Future<void> crateApiScannerSaveAllMetadata({
    required String filePath,
    required String title,
    required String artist,
    required String album,
    String? lyricsText,
    Uint8List? coverData,
  });

  Future<Library> crateApiScannerScanAndUpdateLibrary({
    required String dirPath,
  });

  Future<List<Song>> crateApiScannerScanMusicDirectory({
    required String dirPath,
  });

  Future<List<QQMusicSearchResult>> crateApiMetadataSearchSongOnline({
    required String keyword,
  });

  Future<void> crateApiScannerUpdateSongMetadata({
    required String filePath,
    required String title,
    required String artist,
    required String album,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Uint8List> crateApiMetadataGetCover({required String albummid}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(albummid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMetadataGetCoverConstMeta,
        argValues: [albummid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataGetCoverConstMeta =>
      const TaskConstMeta(debugName: "get_cover", argNames: ["albummid"]);

  @override
  String crateApiMetadataGetCoverUrl({required String albummid}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(albummid, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMetadataGetCoverUrlConstMeta,
        argValues: [albummid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataGetCoverUrlConstMeta =>
      const TaskConstMeta(debugName: "get_cover_url", argNames: ["albummid"]);

  @override
  Library crateApiScannerGetLibrary() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_library,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScannerGetLibraryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScannerGetLibraryConstMeta =>
      const TaskConstMeta(debugName: "get_library", argNames: []);

  @override
  Future<Lyrics> crateApiMetadataGetLyrics({required String songmid}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(songmid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_lyrics,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMetadataGetLyricsConstMeta,
        argValues: [songmid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataGetLyricsConstMeta =>
      const TaskConstMeta(debugName: "get_lyrics", argNames: ["songmid"]);

  @override
  Future<Lyrics> crateApiMetadataGetNeteaseLyrics({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_lyrics,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMetadataGetNeteaseLyricsConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataGetNeteaseLyricsConstMeta =>
      const TaskConstMeta(debugName: "get_netease_lyrics", argNames: ["id"]);

  @override
  int crateApiPlayStatsGetPlayCount({required String filePath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayStatsGetPlayCountConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayStatsGetPlayCountConstMeta =>
      const TaskConstMeta(debugName: "get_play_count", argNames: ["filePath"]);

  @override
  List<PlayCountEntry> crateApiPlayStatsGetPlayStats() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_play_count_entry,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayStatsGetPlayStatsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayStatsGetPlayStatsConstMeta =>
      const TaskConstMeta(debugName: "get_play_stats", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Lyrics crateApiMetadataParseLrcText({required String lrcText}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(lrcText, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_lyrics,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMetadataParseLrcTextConstMeta,
        argValues: [lrcText],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataParseLrcTextConstMeta =>
      const TaskConstMeta(debugName: "parse_lrc_text", argNames: ["lrcText"]);

  @override
  String? crateApiPlayerPlayerGetCurrentFile() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerPlayerGetCurrentFileConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerGetCurrentFileConstMeta =>
      const TaskConstMeta(debugName: "player_get_current_file", argNames: []);

  @override
  double crateApiPlayerPlayerGetVolume() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerPlayerGetVolumeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerGetVolumeConstMeta =>
      const TaskConstMeta(debugName: "player_get_volume", argNames: []);

  @override
  void crateApiPlayerPlayerInit() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerInitConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerInitConstMeta =>
      const TaskConstMeta(debugName: "player_init", argNames: []);

  @override
  bool crateApiPlayerPlayerIsFinished() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerPlayerIsFinishedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerIsFinishedConstMeta =>
      const TaskConstMeta(debugName: "player_is_finished", argNames: []);

  @override
  void crateApiPlayerPlayerPause() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerPauseConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerPauseConstMeta =>
      const TaskConstMeta(debugName: "player_pause", argNames: []);

  @override
  void crateApiPlayerPlayerPlay({required String filePath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerPlayConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerPlayConstMeta =>
      const TaskConstMeta(debugName: "player_play", argNames: ["filePath"]);

  @override
  void crateApiPlayerPlayerResume() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerResumeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerResumeConstMeta =>
      const TaskConstMeta(debugName: "player_resume", argNames: []);

  @override
  void crateApiPlayerPlayerSeek({required double positionSecs}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(positionSecs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerSeekConstMeta,
        argValues: [positionSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerSeekConstMeta =>
      const TaskConstMeta(debugName: "player_seek", argNames: ["positionSecs"]);

  @override
  void crateApiPlayerPlayerSetVolume({required double volume}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(volume, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerSetVolumeConstMeta,
        argValues: [volume],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerSetVolumeConstMeta =>
      const TaskConstMeta(debugName: "player_set_volume", argNames: ["volume"]);

  @override
  void crateApiPlayerPlayerStop() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerStopConstMeta =>
      const TaskConstMeta(debugName: "player_stop", argNames: []);

  @override
  Future<Uint8List?> crateApiScannerReadEmbeddedCover({
    required String filePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScannerReadEmbeddedCoverConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScannerReadEmbeddedCoverConstMeta =>
      const TaskConstMeta(
        debugName: "read_embedded_cover",
        argNames: ["filePath"],
      );

  @override
  Future<String?> crateApiScannerReadEmbeddedLyrics({
    required String filePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScannerReadEmbeddedLyricsConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScannerReadEmbeddedLyricsConstMeta =>
      const TaskConstMeta(
        debugName: "read_embedded_lyrics",
        argNames: ["filePath"],
      );

  @override
  void crateApiPlayStatsRecordPlay({
    required String filePath,
    required String title,
    required String artist,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          sse_encode_String(title, serializer);
          sse_encode_String(artist, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayStatsRecordPlayConstMeta,
        argValues: [filePath, title, artist],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayStatsRecordPlayConstMeta =>
      const TaskConstMeta(
        debugName: "record_play",
        argNames: ["filePath", "title", "artist"],
      );

  @override
  Future<void> crateApiCacheResetLibrary() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCacheResetLibraryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheResetLibraryConstMeta =>
      const TaskConstMeta(debugName: "reset_library", argNames: []);

  @override
  Future<void> crateApiScannerSaveAllMetadata({
    required String filePath,
    required String title,
    required String artist,
    required String album,
    String? lyricsText,
    Uint8List? coverData,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          sse_encode_String(title, serializer);
          sse_encode_String(artist, serializer);
          sse_encode_String(album, serializer);
          sse_encode_opt_String(lyricsText, serializer);
          sse_encode_opt_list_prim_u_8_strict(coverData, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiScannerSaveAllMetadataConstMeta,
        argValues: [filePath, title, artist, album, lyricsText, coverData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScannerSaveAllMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "save_all_metadata",
        argNames: [
          "filePath",
          "title",
          "artist",
          "album",
          "lyricsText",
          "coverData",
        ],
      );

  @override
  Future<Library> crateApiScannerScanAndUpdateLibrary({
    required String dirPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dirPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_library,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiScannerScanAndUpdateLibraryConstMeta,
        argValues: [dirPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScannerScanAndUpdateLibraryConstMeta =>
      const TaskConstMeta(
        debugName: "scan_and_update_library",
        argNames: ["dirPath"],
      );

  @override
  Future<List<Song>> crateApiScannerScanMusicDirectory({
    required String dirPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dirPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_song,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiScannerScanMusicDirectoryConstMeta,
        argValues: [dirPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScannerScanMusicDirectoryConstMeta =>
      const TaskConstMeta(
        debugName: "scan_music_directory",
        argNames: ["dirPath"],
      );

  @override
  Future<List<QQMusicSearchResult>> crateApiMetadataSearchSongOnline({
    required String keyword,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(keyword, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_qq_music_search_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMetadataSearchSongOnlineConstMeta,
        argValues: [keyword],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataSearchSongOnlineConstMeta =>
      const TaskConstMeta(
        debugName: "search_song_online",
        argNames: ["keyword"],
      );

  @override
  Future<void> crateApiScannerUpdateSongMetadata({
    required String filePath,
    required String title,
    required String artist,
    required String album,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          sse_encode_String(title, serializer);
          sse_encode_String(artist, serializer);
          sse_encode_String(album, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiScannerUpdateSongMetadataConstMeta,
        argValues: [filePath, title, artist, album],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScannerUpdateSongMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "update_song_metadata",
        argNames: ["filePath", "title", "artist", "album"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  Library dco_decode_library(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Library(
      songs: dco_decode_list_song(arr[0]),
      scanDirs: dco_decode_list_String(arr[1]),
      lastScanAt: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<LyricLine> dco_decode_list_lyric_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_lyric_line).toList();
  }

  @protected
  List<PlayCountEntry> dco_decode_list_play_count_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_play_count_entry).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<QQMusicSearchResult> dco_decode_list_qq_music_search_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_qq_music_search_result)
        .toList();
  }

  @protected
  List<Singer> dco_decode_list_singer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_singer).toList();
  }

  @protected
  List<Song> dco_decode_list_song(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_song).toList();
  }

  @protected
  LyricLine dco_decode_lyric_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LyricLine(
      timeMs: dco_decode_u_64(arr[0]),
      text: dco_decode_String(arr[1]),
    );
  }

  @protected
  Lyrics dco_decode_lyrics(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return Lyrics(lines: dco_decode_list_lyric_line(arr[0]));
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  PlayCountEntry dco_decode_play_count_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PlayCountEntry(
      filePath: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      artist: dco_decode_String(arr[2]),
      count: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  QQMusicSearchResult dco_decode_qq_music_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return QQMusicSearchResult(
      songmid: dco_decode_String(arr[0]),
      songname: dco_decode_String(arr[1]),
      albummid: dco_decode_String(arr[2]),
      albumname: dco_decode_String(arr[3]),
      singer: dco_decode_list_singer(arr[4]),
      interval: dco_decode_u_64(arr[5]),
    );
  }

  @protected
  Singer dco_decode_singer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Singer(
      id: dco_decode_u_64(arr[0]),
      mid: dco_decode_String(arr[1]),
      name: dco_decode_String(arr[2]),
    );
  }

  @protected
  Song dco_decode_song(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return Song(
      filePath: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      artist: dco_decode_String(arr[2]),
      album: dco_decode_String(arr[3]),
      duration: dco_decode_f_64(arr[4]),
      fileSize: dco_decode_u_64(arr[5]),
      format: dco_decode_String(arr[6]),
      songmid: dco_decode_opt_String(arr[7]),
      albummid: dco_decode_opt_String(arr[8]),
      modifiedAt: dco_decode_u_64(arr[9]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  Library sse_decode_library(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_songs = sse_decode_list_song(deserializer);
    var var_scanDirs = sse_decode_list_String(deserializer);
    var var_lastScanAt = sse_decode_u_64(deserializer);
    return Library(
      songs: var_songs,
      scanDirs: var_scanDirs,
      lastScanAt: var_lastScanAt,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<LyricLine> sse_decode_list_lyric_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LyricLine>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_lyric_line(deserializer));
    }
    return ans_;
  }

  @protected
  List<PlayCountEntry> sse_decode_list_play_count_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PlayCountEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_play_count_entry(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<QQMusicSearchResult> sse_decode_list_qq_music_search_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <QQMusicSearchResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_qq_music_search_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<Singer> sse_decode_list_singer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Singer>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_singer(deserializer));
    }
    return ans_;
  }

  @protected
  List<Song> sse_decode_list_song(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Song>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_song(deserializer));
    }
    return ans_;
  }

  @protected
  LyricLine sse_decode_lyric_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timeMs = sse_decode_u_64(deserializer);
    var var_text = sse_decode_String(deserializer);
    return LyricLine(timeMs: var_timeMs, text: var_text);
  }

  @protected
  Lyrics sse_decode_lyrics(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lines = sse_decode_list_lyric_line(deserializer);
    return Lyrics(lines: var_lines);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlayCountEntry sse_decode_play_count_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_filePath = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_String(deserializer);
    var var_count = sse_decode_u_32(deserializer);
    return PlayCountEntry(
      filePath: var_filePath,
      title: var_title,
      artist: var_artist,
      count: var_count,
    );
  }

  @protected
  QQMusicSearchResult sse_decode_qq_music_search_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_songmid = sse_decode_String(deserializer);
    var var_songname = sse_decode_String(deserializer);
    var var_albummid = sse_decode_String(deserializer);
    var var_albumname = sse_decode_String(deserializer);
    var var_singer = sse_decode_list_singer(deserializer);
    var var_interval = sse_decode_u_64(deserializer);
    return QQMusicSearchResult(
      songmid: var_songmid,
      songname: var_songname,
      albummid: var_albummid,
      albumname: var_albumname,
      singer: var_singer,
      interval: var_interval,
    );
  }

  @protected
  Singer sse_decode_singer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_64(deserializer);
    var var_mid = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    return Singer(id: var_id, mid: var_mid, name: var_name);
  }

  @protected
  Song sse_decode_song(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_filePath = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_String(deserializer);
    var var_album = sse_decode_String(deserializer);
    var var_duration = sse_decode_f_64(deserializer);
    var var_fileSize = sse_decode_u_64(deserializer);
    var var_format = sse_decode_String(deserializer);
    var var_songmid = sse_decode_opt_String(deserializer);
    var var_albummid = sse_decode_opt_String(deserializer);
    var var_modifiedAt = sse_decode_u_64(deserializer);
    return Song(
      filePath: var_filePath,
      title: var_title,
      artist: var_artist,
      album: var_album,
      duration: var_duration,
      fileSize: var_fileSize,
      format: var_format,
      songmid: var_songmid,
      albummid: var_albummid,
      modifiedAt: var_modifiedAt,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_library(Library self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_song(self.songs, serializer);
    sse_encode_list_String(self.scanDirs, serializer);
    sse_encode_u_64(self.lastScanAt, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_lyric_line(
    List<LyricLine> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_lyric_line(item, serializer);
    }
  }

  @protected
  void sse_encode_list_play_count_entry(
    List<PlayCountEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_play_count_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_qq_music_search_result(
    List<QQMusicSearchResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_qq_music_search_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_singer(List<Singer> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_singer(item, serializer);
    }
  }

  @protected
  void sse_encode_list_song(List<Song> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_song(item, serializer);
    }
  }

  @protected
  void sse_encode_lyric_line(LyricLine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.timeMs, serializer);
    sse_encode_String(self.text, serializer);
  }

  @protected
  void sse_encode_lyrics(Lyrics self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_lyric_line(self.lines, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_play_count_entry(
    PlayCountEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.filePath, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.artist, serializer);
    sse_encode_u_32(self.count, serializer);
  }

  @protected
  void sse_encode_qq_music_search_result(
    QQMusicSearchResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.songmid, serializer);
    sse_encode_String(self.songname, serializer);
    sse_encode_String(self.albummid, serializer);
    sse_encode_String(self.albumname, serializer);
    sse_encode_list_singer(self.singer, serializer);
    sse_encode_u_64(self.interval, serializer);
  }

  @protected
  void sse_encode_singer(Singer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.id, serializer);
    sse_encode_String(self.mid, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_song(Song self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.filePath, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.artist, serializer);
    sse_encode_String(self.album, serializer);
    sse_encode_f_64(self.duration, serializer);
    sse_encode_u_64(self.fileSize, serializer);
    sse_encode_String(self.format, serializer);
    sse_encode_opt_String(self.songmid, serializer);
    sse_encode_opt_String(self.albummid, serializer);
    sse_encode_u_64(self.modifiedAt, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
