// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/cache.dart';
import 'api/media_session.dart';
import 'api/metadata.dart';
import 'api/play_stats.dart';
import 'api/player.dart';
import 'api/scanner.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'models/lyrics.dart';
import 'models/song.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  MediaControlEvent dco_decode_box_autoadd_media_control_event(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Library dco_decode_library(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<LyricLine> dco_decode_list_lyric_line(dynamic raw);

  @protected
  List<PlayCountEntry> dco_decode_list_play_count_entry(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Song> dco_decode_list_song(dynamic raw);

  @protected
  LyricLine dco_decode_lyric_line(dynamic raw);

  @protected
  Lyrics dco_decode_lyrics(dynamic raw);

  @protected
  MediaControlEvent dco_decode_media_control_event(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  MediaControlEvent? dco_decode_opt_box_autoadd_media_control_event(
    dynamic raw,
  );

  @protected
  Float32List? dco_decode_opt_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PlayCountEntry dco_decode_play_count_entry(dynamic raw);

  @protected
  Song dco_decode_song(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  MediaControlEvent sse_decode_box_autoadd_media_control_event(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Library sse_decode_library(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<LyricLine> sse_decode_list_lyric_line(SseDeserializer deserializer);

  @protected
  List<PlayCountEntry> sse_decode_list_play_count_entry(
    SseDeserializer deserializer,
  );

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Song> sse_decode_list_song(SseDeserializer deserializer);

  @protected
  LyricLine sse_decode_lyric_line(SseDeserializer deserializer);

  @protected
  Lyrics sse_decode_lyrics(SseDeserializer deserializer);

  @protected
  MediaControlEvent sse_decode_media_control_event(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  MediaControlEvent? sse_decode_opt_box_autoadd_media_control_event(
    SseDeserializer deserializer,
  );

  @protected
  Float32List? sse_decode_opt_list_prim_f_32_strict(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PlayCountEntry sse_decode_play_count_entry(SseDeserializer deserializer);

  @protected
  Song sse_decode_song(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_media_control_event(
    MediaControlEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_library(Library self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_lyric_line(
    List<LyricLine> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_play_count_entry(
    List<PlayCountEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_song(List<Song> self, SseSerializer serializer);

  @protected
  void sse_encode_lyric_line(LyricLine self, SseSerializer serializer);

  @protected
  void sse_encode_lyrics(Lyrics self, SseSerializer serializer);

  @protected
  void sse_encode_media_control_event(
    MediaControlEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_media_control_event(
    MediaControlEvent? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_f_32_strict(
    Float32List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_play_count_entry(
    PlayCountEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_song(Song self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
