// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 初始化系统媒体会话
///
/// Windows 平台需要传入窗口句柄（HWND 转为 i64），macOS 传 0 即可。
/// Android 端此函数为空操作（由原生层处理）。
void mediaSessionInit({required PlatformInt64 hwnd}) =>
    RustLib.instance.api.crateApiMediaSessionMediaSessionInit(hwnd: hwnd);

/// 更新当前播放歌曲的元数据
void mediaSessionUpdateMetadata({
  required String title,
  required String artist,
  required String album,
  required double durationSecs,
}) => RustLib.instance.api.crateApiMediaSessionMediaSessionUpdateMetadata(
  title: title,
  artist: artist,
  album: album,
  durationSecs: durationSecs,
);

/// 更新播放状态（播放中/暂停）
void mediaSessionUpdatePlayback({
  required bool isPlaying,
  required double positionSecs,
}) => RustLib.instance.api.crateApiMediaSessionMediaSessionUpdatePlayback(
  isPlaying: isPlaying,
  positionSecs: positionSecs,
);

/// 设置播放状态为停止
void mediaSessionUpdateStopped() =>
    RustLib.instance.api.crateApiMediaSessionMediaSessionUpdateStopped();

/// 轮询系统媒体控制事件
///
/// 返回 None 表示没有新事件。Flutter 端应定期调用此函数来获取系统媒体键事件。
MediaControlEvent? mediaSessionPollEvent() =>
    RustLib.instance.api.crateApiMediaSessionMediaSessionPollEvent();

/// 媒体控制事件（传递给 Flutter 端）
///
/// action 字段取值：
/// - "play" / "pause" / "toggle" / "next" / "previous" / "stop" / "seek"
///
/// 当 action 为 "seek" 时，position_secs 表示目标位置（秒）
class MediaControlEvent {
  final String action;
  final double positionSecs;

  const MediaControlEvent({required this.action, required this.positionSecs});

  @override
  int get hashCode => action.hashCode ^ positionSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaControlEvent &&
          runtimeType == other.runtimeType &&
          action == other.action &&
          positionSecs == other.positionSecs;
}
