// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/lyrics.dart';
import '../models/song.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 搜索歌曲信息（通过 QQ 音乐接口）
Future<List<QQMusicSearchResult>> searchSongOnline({required String keyword}) =>
    RustLib.instance.api.crateApiMetadataSearchSongOnline(keyword: keyword);

/// 获取歌词（优先从缓存读取，无缓存则在线获取）
Future<Lyrics> getLyrics({required String songmid}) =>
    RustLib.instance.api.crateApiMetadataGetLyrics(songmid: songmid);

/// 获取专辑封面（优先从缓存读取，无缓存则在线下载）
Future<Uint8List> getCover({required String albummid}) =>
    RustLib.instance.api.crateApiMetadataGetCover(albummid: albummid);

/// 获取缓存的封面文件路径
String? getCoverCachePath({required String albummid}) =>
    RustLib.instance.api.crateApiMetadataGetCoverCachePath(albummid: albummid);

/// 获取封面 URL（不下载）
String getCoverUrl({required String albummid}) =>
    RustLib.instance.api.crateApiMetadataGetCoverUrl(albummid: albummid);
