// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/lyrics.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 获取网易云歌词
Future<Lyrics> getNeteaseLyrics({required String id}) =>
    RustLib.instance.api.crateApiMetadataGetNeteaseLyrics(id: id);

/// 解析 LRC 文本为 Lyrics 结构
Lyrics parseLrcText({required String lrcText}) =>
    RustLib.instance.api.crateApiMetadataParseLrcText(lrcText: lrcText);
