// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// 记录一次播放（增加播放次数）
void recordPlay({
  required String filePath,
  required String title,
  required String artist,
}) => RustLib.instance.api.crateApiPlayStatsRecordPlay(
  filePath: filePath,
  title: title,
  artist: artist,
);

/// 获取播放次数排行榜（按播放次数降序）
List<PlayCountEntry> getPlayStats() =>
    RustLib.instance.api.crateApiPlayStatsGetPlayStats();

/// 获取指定歌曲的播放次数
int getPlayCount({required String filePath}) =>
    RustLib.instance.api.crateApiPlayStatsGetPlayCount(filePath: filePath);

/// 播放次数记录项
class PlayCountEntry {
  final String filePath;
  final String title;
  final String artist;
  final int count;

  const PlayCountEntry({
    required this.filePath,
    required this.title,
    required this.artist,
    required this.count,
  });

  @override
  int get hashCode =>
      filePath.hashCode ^ title.hashCode ^ artist.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlayCountEntry &&
          runtimeType == other.runtimeType &&
          filePath == other.filePath &&
          title == other.title &&
          artist == other.artist &&
          count == other.count;
}
