// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 初始化音频引擎
void playerInit() => RustLib.instance.api.crateApiPlayerPlayerInit();

/// 播放指定文件
void playerPlay({required String filePath}) =>
    RustLib.instance.api.crateApiPlayerPlayerPlay(filePath: filePath);

/// 暂停播放
void playerPause() => RustLib.instance.api.crateApiPlayerPlayerPause();

/// 恢复播放
void playerResume() => RustLib.instance.api.crateApiPlayerPlayerResume();

/// 停止播放
void playerStop() => RustLib.instance.api.crateApiPlayerPlayerStop();

/// 跳转到指定位置（秒）
void playerSeek({required double positionSecs}) =>
    RustLib.instance.api.crateApiPlayerPlayerSeek(positionSecs: positionSecs);

/// 设置音量（0.0 ~ 1.0）
void playerSetVolume({required double volume}) =>
    RustLib.instance.api.crateApiPlayerPlayerSetVolume(volume: volume);

/// 获取当前音量
double playerGetVolume() =>
    RustLib.instance.api.crateApiPlayerPlayerGetVolume();

/// 检查是否播放完毕
bool playerIsFinished() =>
    RustLib.instance.api.crateApiPlayerPlayerIsFinished();

/// 获取当前播放文件路径
String? playerGetCurrentFile() =>
    RustLib.instance.api.crateApiPlayerPlayerGetCurrentFile();

/// 获取最新的 64-bin 频谱帧（归一化 0.0~1.0），无帧时返回 None
Float32List? playerGetSpectrum() =>
    RustLib.instance.api.crateApiPlayerPlayerGetSpectrum();

/// 设置播放速度（0.5 ~ 2.0）
void playerSetSpeed({required double speed}) =>
    RustLib.instance.api.crateApiPlayerPlayerSetSpeed(speed: speed);
