// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/song.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `is_audio_file`, `parse_audio_file`

/// 扫描指定目录中的音乐文件
Future<List<Song>> scanMusicDirectory({required String dirPath}) =>
    RustLib.instance.api.crateApiScannerScanMusicDirectory(dirPath: dirPath);

/// 扫描并更新歌曲库（增量更新）
Future<Library> scanAndUpdateLibrary({required String dirPath}) =>
    RustLib.instance.api.crateApiScannerScanAndUpdateLibrary(dirPath: dirPath);

/// 获取当前歌曲库
Library getLibrary() => RustLib.instance.api.crateApiScannerGetLibrary();

/// 更新歌曲元数据（写入文件标签 + 更新本地歌曲库）
Future<void> updateSongMetadata({
  required String filePath,
  required String title,
  required String artist,
  required String album,
}) => RustLib.instance.api.crateApiScannerUpdateSongMetadata(
  filePath: filePath,
  title: title,
  artist: artist,
  album: album,
);

/// 读取文件中嵌入的封面图
Future<Uint8List?> readEmbeddedCover({required String filePath}) =>
    RustLib.instance.api.crateApiScannerReadEmbeddedCover(filePath: filePath);

/// 读取文件中嵌入的歌词文本
Future<String?> readEmbeddedLyrics({required String filePath}) =>
    RustLib.instance.api.crateApiScannerReadEmbeddedLyrics(filePath: filePath);

/// 将所有信息（标题/歌手/专辑/歌词/封面）写入源文件
Future<void> saveAllMetadata({
  required String filePath,
  required String title,
  required String artist,
  required String album,
  String? lyricsText,
  Uint8List? coverData,
}) => RustLib.instance.api.crateApiScannerSaveAllMetadata(
  filePath: filePath,
  title: title,
  artist: artist,
  album: album,
  lyricsText: lyricsText,
  coverData: coverData,
);
